apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openai-secret
  namespace: tshawytscha-ai
spec:
  refreshInterval: 59s
  secretStoreRef:
    name: eso-ro
    kind: ClusterSecretStore
  target:
    name: openai-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: secret/data/tshawytscha-ai
        property: openai-api-key