apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: tschawytscha-ai
spec:
  refreshInterval: 59s
  secretStoreRef:
    name: eso-ro
    kind: ClusterSecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/data/tschawytscha-ai
        property: jwt-secret