apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: 'metrics-server'
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
      targetRevision: 3.13.0
      chart: metrics-server
  project: xavier
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
