# Strategic merge patch for Vault storage configuration
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        storageClassName: ssd-hiiops
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 3Gi
