apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcore-helm-oci-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: eso-ro
    kind: ClusterSecretStore
  target:
    name: gcore-helm-oci-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        name: gcore-helm-oci
        url: registry.luxembourg-2.cloud.gcore.dev/59508-197526-76-infra/aptenbot/charts
        type: helm
        enableOCI: "true"
        username: "{{ .user }}"
        password: "{{ .password }}"
  data:
    - secretKey: user
      remoteRef:
        key: secret/data/registry
        property: user
    - secretKey: password
      remoteRef:
        key: secret/data/registry
        property: password
