apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd
spec:
  destination:
    namespace: 'external-secrets'
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://charts.external-secrets.io'
      targetRevision: v1.2.1
      chart: external-secrets
      helm:
        valueFiles:
          - values.yaml
        valuesObject:
          fullnameOverride: external-secrets
    - repoURL: 'https://github.com/apten-fors/infra.git'
      targetRevision: HEAD
      path: static/xavier/external-secret
  project: xavier
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
