apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
  namespace: argocd
spec:
  destination:
    namespace: 'external-secrets'
    server: 'https://kubernetes.default.svc'
  sources:
    # helm repo add external-secrets https://charts.external-secrets.io
    - repoURL: 'charts.external-secrets.io'
      targetRevision: v1.2.1
      chart: external-secrets
  project: xavier
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
