apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly-operator
  namespace: argocd
spec:
  destination:
    namespace: 'dragonfly-operator'
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'ghcr.io/dragonflydb/dragonfly/helm'
      targetRevision: v1.3.1
      chart: dragonfly-operator
  project: xavier
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
