apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-operator
  namespace: argocd
spec:
  destination:
    namespace: 'openclaw-operator'
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'ghcr.io/openclaw-rocks/charts'
      targetRevision: 0.28.0
      chart: openclaw-operator
  project: xavier
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
