apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aptenbot
  namespace: argocd
spec:
  destination:
    namespace: 'aptenbot'
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'registry.luxembourg-2.cloud.gcore.dev/59508-197526-76-infra/charts'
      chart: aptenbot
      targetRevision: 0.8.0-dev2
      helm:
        valueFiles:
          - $values/static/xavier/aptenbot/values-aptenbot.yaml
    - repoURL: 'https://github.com/apten-fors/infra.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/apten-fors/infra.git'
      targetRevision: HEAD
      path: secrets/xavier/aptenbot/
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
