apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apten-chat-secrets
  namespace: apten-chat
spec:
  refreshInterval: 59s
  secretStoreRef:
    name: eso-ro
    kind: ClusterSecretStore
  target:
    name: apten-chat-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/data/apten-chat
        property: database-url
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/data/apten-chat
        property: jwt-secret
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: secret/data/apten-chat
        property: s3-endpoint
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/data/apten-chat
        property: access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/data/apten-chat
        property: secret-access-key
    - secretKey: VAPID_PUBLIC_KEY
      remoteRef:
        key: secret/data/apten-chat
        property: vapid-public-key
    - secretKey: VAPID_PRIVATE_KEY
      remoteRef:
        key: secret/data/apten-chat
        property: vapid-private-key
