apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  destination:
    namespace: 'envoy-gateway-system'
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'docker.io/envoyproxy'
      targetRevision: v1.6.2
      chart: gateway-helm
  project: xavier
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
