apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apten-claw-secrets
  namespace: apten-claw
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eso-ro
    kind: ClusterSecretStore
  target:
    name: apten-claw-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENCLAW_GCORE_API_KEY
      remoteRef:
        key: secret/data/apten-claw
        property: openclaw-gcore-api-key
    - secretKey: OPENCLAW_OPENAI_API_KEY
      remoteRef:
        key: secret/data/apten-claw
        property: openclaw-openai-api-key
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: secret/data/apten-claw
        property: openclaw-openai-api-key
    - secretKey: OPENCLAW_TELEGRAM_BOT_TOKEN
      remoteRef:
        key: secret/data/apten-claw
        property: openclaw-telegram-bot-token
    - secretKey: GOPLACES_API_KEY
      remoteRef:
        key: secret/data/apten-claw
        property: goplaces-api-key
    - secretKey: OPENAI_WHISPER_API_KEY
      remoteRef:
        key: secret/data/apten-claw
        property: openclaw-openai-api-key
    - secretKey: BRAVE_API_KEY
      remoteRef:
        key: secret/data/apten-claw
        property: brave-api-key
