apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-s3-backup-credentials
  namespace: cnpg-cluster
spec:
  refreshInterval: 59s
  secretStoreRef:
    name: eso-ro
    kind: ClusterSecretStore
  target:
    name: cnpg-s3-backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: secret/data/apten-chat
        property: aws-access-key-id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: secret/data/apten-chat
        property: aws-secret-access-key
