apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: 'cert-manager'
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'quay.io/jetstack/charts'
      targetRevision: v1.19.2
      chart: cert-manager
      helm:
        valueFiles:
          - values.yaml
        valuesObject:
          startupapicheck:
            enabled: false
  project: xavier
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
